# Generated by Django 4.0.1 on 2022-11-06 18:15

from django.db import migrations, models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=400)),
                ('complain', models.CharField(max_length=600)),
            ],
        ),
    ]
